query GetReportsList($options: InvestmentsReportsInput!){
    reports(options: $options){
        fromDate,
        mensualReport,
        reportUri,
        toDate,
        user{
            id,
            email,
            lastName,
            firstName
        }
    }
}