fragment UserSession  on User {
    status
    id
    role
    email
    firstName
    lastName
    favoritesCrypto {
        id
        name
        image
        symbol
        current_price
        market_cap
        price_change_percentage_24h
    }
}
