// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./common/components/organisms/AppSidebar.vue')['default']
    AuthLayout: typeof import('./authentication/components/organisms/AuthLayout.vue')['default']
    CardDoughnut: typeof import('./dashboard/components/organisms/CardDoughnut.vue')['default']
    CardSolde: typeof import('./dashboard/components/organisms/cardSolde.vue')['default']
    Chip: typeof import('./common/components/atoms/Chip.vue')['default']
    CodeInput: typeof import('./authentication/components/organisms/CodeInput.vue')['default']
    CryptoDetailsArticle: typeof import('./crypto/components/molecules/CryptoDetailsArticle.vue')['default']
    CryptoDetailsConversion: typeof import('./crypto/components/molecules/CryptoDetailsConversion.vue')['default']
    CryptoDetailsConversionInput: typeof import('./crypto/components/atoms/CryptoDetailsConversionInput.vue')['default']
    CryptoDetailsGraph: typeof import('./crypto/components/molecules/CryptoDetailsGraph.vue')['default']
    CryptoDetailsHeader: typeof import('./crypto/components/molecules/CryptoDetailsHeader.vue')['default']
    CryptoDetailsInformation: typeof import('./crypto/components/organims/CryptoDetailsInformation.vue')['default']
    CryptoDetailsNews: typeof import('./crypto/components/organims/CryptoDetailsNews.vue')['default']
    CryptoDetailsStat: typeof import('./crypto/components/atoms/CryptoDetailsStat.vue')['default']
    CryptoDetailsTabs: typeof import('./crypto/components/organims/CryptoDetailsTabs.vue')['default']
    CryptoList: typeof import('./market/components/organisms/CryptoList.vue')['default']
    CsimLogo: typeof import('./common/components/atoms/CsimLogo.vue')['default']
    DashboardFavorites: typeof import('./dashboard/components/organisms/DashboardFavorites.vue')['default']
    Doughnuts: typeof import('./dashboard/components/molecules/doughnuts.vue')['default']
    Error404: typeof import('./common/components/molecules/Error404.vue')['default']
    Error500: typeof import('./common/components/molecules/Error500.vue')['default']
    FileInput: typeof import('./investments/components/atoms/FileInput.vue')['default']
    Footer: typeof import('./common/components/organisms/Footer.vue')['default']
    Header: typeof import('./common/components/organisms/Header.vue')['default']
    Infos: typeof import('./common/components/organisms/Infos.vue')['default']
    InvestmentFilesDrop: typeof import('./investments/components/organisms/InvestmentFilesDrop.vue')['default']
    InvestmentList: typeof import('./investments/components/organisms/InvestmentList.vue')['default']
    LoadingPage: typeof import('./common/components/organisms/LoadingPage.vue')['default']
    PasswordInput: typeof import('./common/components/molecules/PasswordInput.vue')['default']
    ReportsList: typeof import('./investments/components/organisms/ReportsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./profile/components/organisms/Settings.vue')['default']
    SidebarItem: typeof import('./investments/components/molecules/SidebarItem.vue')['default']
    Spinner: typeof import('./common/components/molecules/Spinner.vue')['default']
    TextInput: typeof import('./common/components/molecules/TextInput.vue')['default']
  }
}

export {}
